"""rename address

Revision ID: 79712006de9a
Revises: ea60c64414f2
Create Date: 2025-09-07 20:32:35.772845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79712006de9a'
down_revision = 'ea60c64414f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
